on:
  pull_request:
    types:
      - closed
    branches:
      - master
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: echo The PR was merged so lets add that to the test branch
    - run: echo Change some things
    - name: merge into test
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        github_token: ${{ github.token }}
        source: 'master'
        target: 'test'
